version: '3.8'
services:
  task-01:
    build:
      context: ./
      dockerfile: Dockerfile    
    # ports:
    # - 8080:8080   
    networks:
      - mainnet

  nginx:
    image: "nginx:1.23.1"
    environment:
      - PORT=8080
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf.template:ro

    ports:
      - "80:80"

    networks:
      - mainnet

    depends_on:
      - "task-01"
    command: /bin/bash -c "envsubst < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"


networks:
  mainnet:
    driver: bridge
