version: 2.1

orbs:
  slack: circleci/slack@4.9.3
jobs:
  # notify:
  #   docker:
  #     - image: 'cimg/base:stable'
  #       # auth:
  #       #   username: $DOCKERHUB_USERNAME
  #       #   password: $DOCKERHUB_PASS  # context / project UI env-var reference
  #   steps:
  #     - slack/notify:
  #           event: fail
  #           template: basic_fail_1
         
  test:
    docker:
      - image: circleci/golang:1.15.8
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            gofmt -e 2main.go
            go build -v ./...
      
      - slack/notify:
            event: fail
            template: basic_fail_1
  build:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image and Publish Docker Image to Docker Hub
          command: |
            docker build --tag $DOCKERHUB_REPO . 
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $DOCKERHUB_REPO

workflows:
  godockerci: 
    jobs:
      - test:
          context: task-01context
          filters:
            branches:
              only:
                - main
                - dev
            tags:
              only: \d{1,2}\.\d{1,2}\.\d{1,2}

      - build:
          context: task-01context
          filters:
            branches:
              only:
                - main
                - dev
            tags:
              only: \d{1,2}\.\d{1,2}\.\d{1,2}

      # - notify:
      #     context: task-01context
      #     filters:
      #       branches:
      #         only:
      #           - main
      #           - dev
      #       tags:
      #         only: \d{1,2}\.\d{1,2}\.\d{1,2}      
