name: CI-task

on:
  push:
    branches: [ "main" , "dev" ]
    tags: 
      - '\d{1,2}\.\d{1,2}\.\d{1,2}'
  pull_request:
    branches: [ "main" , "dev" ]
    tags: 
      - '\d{1,2}\.\d{1,2}\.\d{1,2}'
      

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.13.8
    - name: Test
      run: gofmt -e 2main.go
      
    - name: Build
      run: go build -v ./...
      
    - name: Report Status
      if: always()
      uses: ravsamhq/notify-slack-action@v1
      with:
        status: ${{ job.status }}
        notify_when: 'failure'
        notification_title: '{workflow} has {status_message}'
#         message_format: '{emoji} *{workflow}* {status_message} in <{repo_url}|{repo}>'
        footer: 'Linked to Repo <{repo_url}|{repo}>'
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}      
      
  build:

    runs-on: ubuntu-latest
    needs: [test]
    steps:
    - uses: actions/checkout@v3
    
    - name: Docker Login
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
#     - name: Build the Docker image
#       run: docker build --tag ${{ github.event.repository.name }} .

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}
    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
    - name: Report Status
      if: always()
      uses: ravsamhq/notify-slack-action@v1
      with:
        status: ${{ job.status }}
        notify_when: 'failure'
        notification_title: '{workflow} has {status_message}'
        message_format: '{emoji} *{workflow}* {status_message} in <{repo_url}|{repo}>'
        footer: 'Linked to Repo <{repo_url}|{repo}>'
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}        
  
#   check:
#     runs-on: ubuntu-latest
#     if: always()
#     needs: [test,build]
#     steps:
#     - name: Report Status
#       if: always()
#       uses: ravsamhq/notify-slack-action@v1
#       with:
#         status: ${{ job.status }}
#         notify_when: 'failure'
#         notification_title: '{workflow} has {status_message}'
#         message_format: '{emoji} *{workflow}* {status_message} in <{repo_url}|{repo}>'
#         footer: 'Linked to Repo <{repo_url}|{repo}>'
#       env:
#         SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}


