name: CI-task

on:
  push:
    branches: [ "main" , "dev" ]
  pull_request:
    branches: [ "main" , "dev" ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.13.8
    - name: Test
      run: gofmt -e main.go
      
    - name: Build
      run: go build -v ./...
      
  build:

    runs-on: ubuntu-latest
    needs: [test]
    steps:
    - uses: actions/checkout@v3
    
    - name: Docker Login
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build the Docker image
      run: docker build --tag my-image-name .
    
    - name: test of env
      run: |
       echo "REPO_NAME=${{ github.event.repository.name }}" 
       echo "hello $REPO_NAME"


